In [1]:
import pandas as pd

In [2]:
a = pd.read_json("Data/Location History.json")

In [6]:
a.to_csv("Data/jsonToCSV")

In [7]:
a

                                                locations
0       {'timestampMs': '1507082075674', 'latitudeE7':...
1       {'timestampMs': '1507081714453', 'latitudeE7':...
2       {'timestampMs': '1507081331168', 'latitudeE7':...
3       {'timestampMs': '1507080970091', 'latitudeE7':...
4       {'timestampMs': '1507080608977', 'latitudeE7':...
5       {'timestampMs': '1507080205185', 'latitudeE7':...
6       {'timestampMs': '1507079844156', 'latitudeE7':...
7       {'timestampMs': '1507079482936', 'latitudeE7':...
8       {'timestampMs': '1507079121936', 'latitudeE7':...
9       {'timestampMs': '1507078760912', 'latitudeE7':...
10      {'timestampMs': '1507078399810', 'latitudeE7':...
11      {'timestampMs': '1507078038773', 'latitudeE7':...
12      {'timestampMs': '1507077644056', 'latitudeE7':...
13      {'timestampMs': '1507077283058', 'latitudeE7':...
14      {'timestampMs': '1507076921895', 'latitudeE7':...
15      {'timestampMs': '1507076560946', 'latitudeE7':...
16      {'timestampMs': '1507076199854', 'latitudeE7':...
17      {'timestampMs': '1507075838802', 'latitudeE7':...
18      {'timestampMs': '1507075477747', 'latitudeE7':...
19      {'timestampMs': '1507075109048', 'latitudeE7':...
20      {'timestampMs': '1507074709775', 'latitudeE7':...
21      {'timestampMs': '1507074348769', 'latitudeE7':...
22      {'timestampMs': '1507073959916', 'latitudeE7':...
23      {'timestampMs': '1507073598896', 'latitudeE7':...
24      {'timestampMs': '1507073237794', 'latitudeE7':...
25      {'timestampMs': '1507072841043', 'latitudeE7':...
26      {'timestampMs': '1507072479937', 'latitudeE7':...
27      {'timestampMs': '1507072118949', 'latitudeE7':...
28      {'timestampMs': '1507071757885', 'latitudeE7':...
29      {'timestampMs': '1507071396886', 'latitudeE7':...
...                                                   ...
587853  {'timestampMs': '1432734525429', 'latitudeE7':...
587854  {'timestampMs': '1432734479416', 'latitudeE7':...
587855  {'timestampMs': '1432734433395', 'latitudeE7':...
587856  {'timestampMs': '1432734388161', 'latitudeE7':...
587857  {'timestampMs': '1432734342660', 'latitudeE7':...
587858  {'timestampMs': '1432734297394', 'latitudeE7':...
587859  {'timestampMs': '1432734251391', 'latitudeE7':...
587860  {'timestampMs': '1432734205411', 'latitudeE7':...
587861  {'timestampMs': '1432734159436', 'latitudeE7':...
587862  {'timestampMs': '1432734114414', 'latitudeE7':...
587863  {'timestampMs': '1432734069353', 'latitudeE7':...
587864  {'timestampMs': '1432734023433', 'latitudeE7':...
587865  {'timestampMs': '1432733978411', 'latitudeE7':...
587866  {'timestampMs': '1432733932564', 'latitudeE7':...
587867  {'timestampMs': '1432733886981', 'latitudeE7':...
587868  {'timestampMs': '1432733841926', 'latitudeE7':...
587869  {'timestampMs': '1432728150452', 'latitudeE7':...
587870  {'timestampMs': '1432728104984', 'latitudeE7':...
587871  {'timestampMs': '1432728021540', 'latitudeE7':...
587872  {'timestampMs': '1432727975745', 'latitudeE7':...
587873  {'timestampMs': '1432727930443', 'latitudeE7':...
587874  {'timestampMs': '1432727884481', 'latitudeE7':...
587875  {'timestampMs': '1432727838685', 'latitudeE7':...
587876  {'timestampMs': '1432727792206', 'latitudeE7':...
587877  {'timestampMs': '1432727747197', 'latitudeE7':...
587878  {'timestampMs': '1432727701368', 'latitudeE7':...
587879  {'timestampMs': '1432727656223', 'latitudeE7':...
587880  {'timestampMs': '1432727611203', 'latitudeE7':...
587881  {'timestampMs': '1432727565389', 'latitudeE7':...
587882  {'timestampMs': '1432727519907', 'latitudeE7':...

[587883 rows x 1 columns]

In [8]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 587883 entries, 0 to 587882
Data columns (total 1 columns):
locations    587883 non-null object
dtypes: object(1)
memory usage: 4.5+ MB